WIP: Resilience
ORNL/intersect-architecture pull request #42
Opened 2024-10-28 19:09 UTC by engelmannc

2025-03-27 21:20 UTC, MichaelBrim requested changes
I pushed a commit with minor edits/fixes. I made a couple comments on things that I think need further attention.

2025-03-27 23:39 UTC, engelmannc commented on sos/logical/resilience/index.rst
> +on the system by design and not on the operator or user as an afterthought.
This sentence is mostly about designing solutions based on actual resilience needs, which may differ widely, depending on the involved hardware/software. See: https://intersect-architecture--42.org.readthedocs.build/en/42/sos/logical/errors.html for the definition of User-defined response.

2025-03-27 23:39 UTC, engelmannc commented on sos/logical/resilience/index.rst
> +User-Defined Responses
See: https://intersect-architecture--42.org.readthedocs.build/en/42/sos/logical/errors.html for the definition of User-defined response.

2025-03-31 15:26 UTC, engelmannc commented on sos/logical/resilience/index.rst
> +on the system by design and not on the operator or user as an afterthought.
See the latest commit on this. I changed the language to be more coherent and avoided the confusion of user-defined responses.

2025-03-31 15:27 UTC, engelmannc commented on sos/logical/resilience/index.rst
> +User-Defined Responses
See the latest commit on this. I changed the language to be more coherent and avoided the confusion of user-defined responses.

2025-03-31 18:18 UTC, MichaelBrim approved these changes

2025-03-31 18:25 UTC, merged